# Generated by Django 4.2.1 on 2023-07-15 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id_customer', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('telephone', models.IntegerField()),
                ('email', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('category', models.TextField(max_length=300)),
                ('quantity_stock', models.IntegerField()),
                ('unitary_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_Authentication',
            fields=[
                ('id_user', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('name', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=30)),
                ('cellphone', models.IntegerField()),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id_sell', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price_sell', models.IntegerField()),
                ('quantity_sell', models.IntegerField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppComercios.customers')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAppComercios.products')),
            ],
        ),
    ]
