# Generated by Django 4.2.1 on 2023-07-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppComercios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_authentication',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='users_authentication',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users_authentication',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users_authentication',
            name='user',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
